data_dir: "data/raw/"
img_height: 224
img_width: 224
batch_size: 16
validation_split: 0.2
test_split: 0.1
augmentation:
  enable: true
  rotation_prob: 0.5
  brightness_prob: 0.5
  brightness_max_delta: 0.2
  contrast_prob: 0.5
  contrast_lower: 0.5
  contrast_upper: 1.5
  saturation_prob: 0.5
  saturation_lower: 0.5
  saturation_upper: 1.5
  flip_prob: 0.5