input_shape: [224, 224, 1]
num_classes: 4
backbone: "DenseNet169"   # Options: DenseNet169 or DenseNet201
freeze_base: true
dropout_rate: 0.3
learning_rate: 1e-4
fine_tune_lr: 1e-5
epochs_head: 10
epochs_fine: 20